# Generated by Django 2.1 on 2019-04-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_sets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorset',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutorset',
            name='totalQuestions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
