# Generated by Django 2.1 on 2019-04-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_sets', '0004_auto_20190424_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='prompt',
        ),
        migrations.RemoveField(
            model_name='option',
            name='optionText',
        ),
        migrations.AddField(
            model_name='option',
            name='option',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
