# Generated by Django 2.1 on 2019-04-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_sets', '0005_auto_20190424_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tutorSetID',
            new_name='tutorSet',
        ),
    ]
