# Generated by Django 2.1 on 2019-04-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_sets', '0008_auto_20190425_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='shuffle_answers',
            field=models.BooleanField(default=False),
        ),
    ]
