# Generated by Django 2.1 on 2019-04-26 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_sets', '0010_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='tutorSet',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
    ]
