# Generated by Django 2.1 on 2019-04-27 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor_sets', '0011_auto_20190426_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberCorrect', models.IntegerField(default=0)),
                ('totalQuestions', models.IntegerField(default=0)),
                ('tutorSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_sets.TutorSet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
