# Generated by Django 2.2 on 2019-04-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_sets', '0012_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
