# Generated by Django 2.2 on 2019-04-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_sets', '0014_auto_20190429_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='tutorset',
            name='description',
        ),
        migrations.AddField(
            model_name='option',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='shuffle_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorset',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutorset',
            name='totalQuestions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
