# Generated by Django 2.2 on 2019-04-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_sets', '0016_auto_20190429_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attempt',
        ),
    ]
