# Generated by Django 2.2 on 2019-04-30 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_sets', '0017_delete_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorset',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorset',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
