# Generated by Django 2.1 on 2019-04-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorSet',
        ),
    ]
